steps:
# Docker build
# =================================================================
- id: docker-build-push
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - '-c'
  - |
    docker build -t "gcr.io/project-kubernetes-242705/welcome:$SHORT_SHA" .
    docker push "gcr.io/project-kubernetes-242705/welcome:$SHORT_SHA"
# Kubernetes
# =================================================================
- id: kubectl-set-image
  name: gcr.io/cloud-builders/kubectl
  args: ['set', 'image', 'deployment/projectname', 'projectname=gcr.io/project-kubernetes-242705/welcome:$SHORT_SHA']
  waitFor: ['docker-build-push']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=poc-cluster'
# Machine type - change this if you need more firepower
# =================================================================
