---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: welcome-demo
  name: welcome-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      run: welcome-demo
  template:
    metadata:
      labels:
        run: welcome-demo
    spec:
      containers:
      - image: gcr.io/find-seller-app-dev-237005/github.com/ffaisalahmedd/welcome-demo
        name: welcome-demo
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: projectname
spec:
  type: ClusterIP
  selector:
    app: projectname
  ports:
  - name: http
    port: 80
    targetPort: 8888
