---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: projectname
  labels:
    app: projectname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectname
  template:
    metadata:
      name: projectname
      labels:
        app: projectname
    spec:
      containers:
        - name: projectname
          image: eu.gcr.io/[PROJECT_ID]/projectname:[TAG]
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: projectname
spec:
  type: ClusterIP
  selector:
    app: projectname
  ports:
  - name: http
    port: 80
    targetPort: 8888
